import type { Match } from '@models/match';
import type { Player } from '@models/player';
import type { Season } from '@models/season';
import type { Stadium } from '@models/stadium';
import type { Team } from '@models/team';

export const teams: Team[] = [
  {
    id: 'blue-horses',
    name: 'Blue Horses',
  },
];

export const stadiums: Stadium[] = [
  {
    id: 'vodova-arena',
    name: 'Vodova Arena',
  },
  {
    id: 'jih-rink',
    name: 'Jih Rink',
  },
  {
    id: 'horses-dome',
    name: 'Horses Dome',
  },
];

export const seasons: Season[] = [
  {
    id: '2022-2023',
    year: '2022/2023',
    team: 'Blue Horses',
    leagueLevel: 2,
    leagueName: 'Městská liga Brno',
    position: 5,
    covidInterrupted: false,
  },
  {
    id: '2023-2024',
    year: '2023/2024',
    team: 'Blue Horses',
    leagueLevel: 2,
    leagueName: 'Městská liga Brno',
    position: 3,
    covidInterrupted: false,
  },
  {
    id: '2024-2025',
    year: '2024/2025',
    team: 'Blue Horses',
    leagueLevel: 1,
    leagueName: 'Jihomoravská elitní liga',
    position: 2,
    covidInterrupted: false,
  },
];

export const players: Player[] = [
  {
    id: 'stanislav-prokop',
    name: 'Stanislav Prokop',
    number: '9',
    position: 'forward',
    squads: ['A'],
  },
  {
    id: 'jiri-polivka',
    name: 'Jiří Polívka',
    number: '18',
    position: 'forward',
    squads: ['A', 'B'],
  },
  {
    id: 'jakub-vlcek',
    name: 'Jakub Vlček',
    number: '27',
    position: 'defender',
    squads: ['A', 'B'],
  },
  {
    id: 'marek-kucera',
    name: 'Marek Kučera',
    number: '1',
    position: 'goalie',
    squads: ['A', 'B', 'C'],
  },
  {
    id: 'ondrej-simacek',
    name: 'Ondřej Šimáček',
    number: '11',
    position: 'utility',
    squads: ['B', 'C'],
  },
  {
    id: 'tomas-sedlacek',
    name: 'Tomáš Sedláček',
    number: '14',
    position: 'forward',
    squads: ['C'],
  },
];

export const matches: Match[] = [
  {
    id: 'bh-vs-falcons-2023-11-12',
    squad: 'A',
    stadiumId: 'vodova-arena',
    date: '2023-11-12',
    opponent: 'Brno Falcons',
    seasonId: '2023-2024',
    homeGame: true,
    matchLength: 36,
    ourScore: 5,
    opponentScore: 3,
    result: 'W',
    presentPlayerIds: ['stanislav-prokop', 'jiri-polivka', 'jakub-vlcek', 'marek-kucera', 'ondrej-simacek'],
    goalieMinutes: [
      {
        playerId: 'marek-kucera',
        minutesPlayed: 36,
      },
    ],
    goals: [
      {
        id: 'g1',
        type: 'even strength',
        time: 4,
        scorerId: 'stanislav-prokop',
        assistId: 'jiri-polivka',
        matchId: 'bh-vs-falcons-2023-11-12',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g2',
        type: 'even strength',
        time: 11,
        scorerId: 'jiri-polivka',
        assistId: 'jakub-vlcek',
        matchId: 'bh-vs-falcons-2023-11-12',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: true,
      },
      {
        id: 'g3',
        type: 'power play',
        time: 17,
        scorerId: null,
        assistId: null,
        matchId: 'bh-vs-falcons-2023-11-12',
        ourTeam: false,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g4',
        type: 'even strength',
        time: 23,
        scorerId: 'ondrej-simacek',
        assistId: 'stanislav-prokop',
        matchId: 'bh-vs-falcons-2023-11-12',
        ourTeam: true,
        winningGoal: true,
        equalizingGoal: false,
      },
      {
        id: 'g5',
        type: 'even strength',
        time: 29,
        scorerId: null,
        assistId: null,
        matchId: 'bh-vs-falcons-2023-11-12',
        ourTeam: false,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g6',
        type: 'even strength',
        time: 31,
        scorerId: 'tomas-sedlacek',
        assistId: 'ondrej-simacek',
        matchId: 'bh-vs-falcons-2023-11-12',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g7',
        type: 'empty net',
        time: 35,
        scorerId: 'stanislav-prokop',
        assistId: null,
        matchId: 'bh-vs-falcons-2023-11-12',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g8',
        type: 'power play',
        time: 36,
        scorerId: null,
        assistId: null,
        matchId: 'bh-vs-falcons-2023-11-12',
        ourTeam: false,
        winningGoal: false,
        equalizingGoal: false,
      },
    ],
    penalties: [
      {
        id: 'p1',
        type: 'hooking',
        time: 9,
        penaltyMinutes: 2,
        playerId: 'jakub-vlcek',
        matchId: 'bh-vs-falcons-2023-11-12',
        ourTeam: true,
      },
      {
        id: 'p2',
        type: 'tripping',
        time: 18,
        penaltyMinutes: 2,
        playerId: null,
        matchId: 'bh-vs-falcons-2023-11-12',
        ourTeam: false,
      },
    ],
  },
  {
    id: 'bh-vs-wolves-2024-02-04',
    squad: 'B',
    stadiumId: 'jih-rink',
    date: '2024-02-04',
    opponent: 'South Wolves',
    seasonId: '2023-2024',
    homeGame: false,
    matchLength: 36,
    ourScore: 2,
    opponentScore: 2,
    result: 'D',
    presentPlayerIds: ['stanislav-prokop', 'jiri-polivka', 'jakub-vlcek', 'marek-kucera', 'tomas-sedlacek'],
    goalieMinutes: [
      {
        playerId: 'marek-kucera',
        minutesPlayed: 36,
      },
    ],
    goals: [
      {
        id: 'g9',
        type: 'even strength',
        time: 7,
        scorerId: null,
        assistId: null,
        matchId: 'bh-vs-wolves-2024-02-04',
        ourTeam: false,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g10',
        type: 'even strength',
        time: 14,
        scorerId: 'jiri-polivka',
        assistId: 'stanislav-prokop',
        matchId: 'bh-vs-wolves-2024-02-04',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: true,
      },
      {
        id: 'g11',
        type: 'shorthanded',
        time: 22,
        scorerId: 'stanislav-prokop',
        assistId: 'jakub-vlcek',
        matchId: 'bh-vs-wolves-2024-02-04',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g12',
        type: 'even strength',
        time: 33,
        scorerId: null,
        assistId: null,
        matchId: 'bh-vs-wolves-2024-02-04',
        ourTeam: false,
        winningGoal: false,
        equalizingGoal: true,
      },
    ],
    penalties: [
      {
        id: 'p3',
        type: 'roughing',
        time: 21,
        penaltyMinutes: 2,
        playerId: 'tomas-sedlacek',
        matchId: 'bh-vs-wolves-2024-02-04',
        ourTeam: true,
      },
    ],
  },
  {
    id: 'bh-vs-ravens-2024-09-15',
    squad: 'B',
    stadiumId: 'horses-dome',
    date: '2024-09-15',
    opponent: 'Prague Ravens',
    seasonId: '2024-2025',
    homeGame: true,
    matchLength: 36,
    ourScore: 6,
    opponentScore: 1,
    result: 'W',
    presentPlayerIds: ['stanislav-prokop', 'jiri-polivka', 'jakub-vlcek', 'marek-kucera', 'ondrej-simacek', 'tomas-sedlacek'],
    goalieMinutes: [
      {
        playerId: 'marek-kucera',
        minutesPlayed: 36,
      },
    ],
    goals: [
      {
        id: 'g13',
        type: 'even strength',
        time: 2,
        scorerId: 'tomas-sedlacek',
        assistId: 'ondrej-simacek',
        matchId: 'bh-vs-ravens-2024-09-15',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g14',
        type: 'power play',
        time: 6,
        scorerId: 'stanislav-prokop',
        assistId: 'jiri-polivka',
        matchId: 'bh-vs-ravens-2024-09-15',
        ourTeam: true,
        winningGoal: true,
        equalizingGoal: false,
      },
      {
        id: 'g15',
        type: 'even strength',
        time: 16,
        scorerId: 'ondrej-simacek',
        assistId: 'jakub-vlcek',
        matchId: 'bh-vs-ravens-2024-09-15',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g16',
        type: 'even strength',
        time: 24,
        scorerId: null,
        assistId: null,
        matchId: 'bh-vs-ravens-2024-09-15',
        ourTeam: false,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g17',
        type: 'even strength',
        time: 28,
        scorerId: 'jiri-polivka',
        assistId: 'stanislav-prokop',
        matchId: 'bh-vs-ravens-2024-09-15',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g18',
        type: 'even strength',
        time: 31,
        scorerId: 'stanislav-prokop',
        assistId: 'tomas-sedlacek',
        matchId: 'bh-vs-ravens-2024-09-15',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g19',
        type: 'even strength',
        time: 34,
        scorerId: 'jakub-vlcek',
        assistId: 'jiri-polivka',
        matchId: 'bh-vs-ravens-2024-09-15',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
    ],
    penalties: [
      {
        id: 'p4',
        type: 'holding',
        time: 10,
        penaltyMinutes: 2,
        playerId: 'ondrej-simacek',
        matchId: 'bh-vs-ravens-2024-09-15',
        ourTeam: true,
      },
    ],
  },
  {
    id: 'bh-vs-titans-2024-11-03',
    squad: 'A',
    stadiumId: 'vodova-arena',
    date: '2024-11-03',
    opponent: 'Olomouc Titans',
    seasonId: '2024-2025',
    homeGame: false,
    matchLength: 36,
    ourScore: 3,
    opponentScore: 4,
    result: 'L',
    presentPlayerIds: ['stanislav-prokop', 'jiri-polivka', 'jakub-vlcek', 'marek-kucera', 'ondrej-simacek'],
    goalieMinutes: [
      {
        playerId: 'marek-kucera',
        minutesPlayed: 36,
      },
    ],
    goals: [
      {
        id: 'g20',
        type: 'even strength',
        time: 3,
        scorerId: null,
        assistId: null,
        matchId: 'bh-vs-titans-2024-11-03',
        ourTeam: false,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g21',
        type: 'even strength',
        time: 12,
        scorerId: 'stanislav-prokop',
        assistId: 'jiri-polivka',
        matchId: 'bh-vs-titans-2024-11-03',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: true,
      },
      {
        id: 'g22',
        type: 'power play',
        time: 18,
        scorerId: 'jiri-polivka',
        assistId: 'jakub-vlcek',
        matchId: 'bh-vs-titans-2024-11-03',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g23',
        type: 'even strength',
        time: 20,
        scorerId: null,
        assistId: null,
        matchId: 'bh-vs-titans-2024-11-03',
        ourTeam: false,
        winningGoal: false,
        equalizingGoal: true,
      },
      {
        id: 'g24',
        type: 'even strength',
        time: 27,
        scorerId: 'ondrej-simacek',
        assistId: 'stanislav-prokop',
        matchId: 'bh-vs-titans-2024-11-03',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: true,
      },
      {
        id: 'g25',
        type: 'power play',
        time: 30,
        scorerId: null,
        assistId: null,
        matchId: 'bh-vs-titans-2024-11-03',
        ourTeam: false,
        winningGoal: true,
        equalizingGoal: false,
      },
      {
        id: 'g26',
        type: 'empty net',
        time: 36,
        scorerId: null,
        assistId: null,
        matchId: 'bh-vs-titans-2024-11-03',
        ourTeam: false,
        winningGoal: false,
        equalizingGoal: false,
      },
    ],
    penalties: [
      {
        id: 'p5',
        type: 'interference',
        time: 8,
        penaltyMinutes: 2,
        playerId: 'stanislav-prokop',
        matchId: 'bh-vs-titans-2024-11-03',
        ourTeam: true,
      },
      {
        id: 'p6',
        type: 'too many players',
        time: 29,
        penaltyMinutes: 2,
        playerId: null,
        matchId: 'bh-vs-titans-2024-11-03',
        ourTeam: false,
      },
    ],
  },
  {
    id: 'bh-vs-comets-2025-01-19',
    squad: 'C',
    stadiumId: 'horses-dome',
    date: '2025-01-19',
    opponent: 'Zlín Comets',
    seasonId: '2024-2025',
    homeGame: true,
    matchLength: 36,
    ourScore: 4,
    opponentScore: 1,
    result: 'W',
    presentPlayerIds: ['stanislav-prokop', 'jiri-polivka', 'jakub-vlcek', 'marek-kucera', 'ondrej-simacek', 'tomas-sedlacek'],
    goalieMinutes: [
      {
        playerId: 'marek-kucera',
        minutesPlayed: 36,
      },
    ],
    goals: [
      {
        id: 'g27',
        type: 'power play',
        time: 5,
        scorerId: 'jiri-polivka',
        assistId: 'stanislav-prokop',
        matchId: 'bh-vs-comets-2025-01-19',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g28',
        type: 'even strength',
        time: 14,
        scorerId: 'tomas-sedlacek',
        assistId: 'ondrej-simacek',
        matchId: 'bh-vs-comets-2025-01-19',
        ourTeam: true,
        winningGoal: true,
        equalizingGoal: false,
      },
      {
        id: 'g29',
        type: 'even strength',
        time: 21,
        scorerId: null,
        assistId: null,
        matchId: 'bh-vs-comets-2025-01-19',
        ourTeam: false,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g30',
        type: 'even strength',
        time: 24,
        scorerId: 'stanislav-prokop',
        assistId: 'jakub-vlcek',
        matchId: 'bh-vs-comets-2025-01-19',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
      {
        id: 'g31',
        type: 'empty net',
        time: 35,
        scorerId: 'ondrej-simacek',
        assistId: null,
        matchId: 'bh-vs-comets-2025-01-19',
        ourTeam: true,
        winningGoal: false,
        equalizingGoal: false,
      },
    ],
    penalties: [
      {
        id: 'p7',
        type: 'slashing',
        time: 19,
        penaltyMinutes: 2,
        playerId: 'jakub-vlcek',
        matchId: 'bh-vs-comets-2025-01-19',
        ourTeam: true,
      },
    ],
  },
];